#!/bin/sh
#place in /usr/lib/systemd/system-sleep/
#make executable: chmod +x /usr/lib/systemd/system-sleep/atarivt.sh



case "$1" in
    pre)
        ;;
    post)
        # Commands to run AFTER the system wakes up
        sudo -i -u praxis sh -c '/home/praxis/git/karai/atarivt/atarivt.sh' &
        ;;
esac
